# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
