# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20160325_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exp_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 4, 9, 24, 37, 469673)),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
