# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20160404_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exp_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 4, 9, 53, 39, 899603)),
        ),
    ]
