# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20160404_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exp_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 7, 10, 46, 32, 371792)),
        ),
    ]
