# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20160407_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='exp_time',
        ),
    ]
